// <auto-generated />
using System;
using Dynamo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DecathlonDynamoErpApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200417163641_PLBUpdate")]
    partial class PLBUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dynamo.Model.CICalendar.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllDay");

                    b.Property<string>("CreatedByUserId");

                    b.Property<string>("Description");

                    b.Property<string>("FromDate");

                    b.Property<string>("StatusColour");

                    b.Property<string>("Title");

                    b.Property<string>("ToDate");

                    b.HasKey("Id");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("Dynamo.Model.CICalendar.EventGuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CalendarEventId");

                    b.Property<int>("Status");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CalendarEventId");

                    b.ToTable("EventGuests");
                });

            modelBuilder.Entity("Dynamo.Model.Common.Authentication.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "f686b56a-6135-4221-a0b0-bdec547e3waw",
                            ConcurrencyStamp = "da9a3b0e-8b6f-8529-71d0-4fd255e23f15",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has All Permissions",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "w585b57b-7456-8222-c0d0-bdec765e3awa",
                            ConcurrencyStamp = "ea9a3b0f-9b5f-7153-81e0-4fd799e23f16",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Maximum Permissions",
                            Name = "MAFAdmin",
                            NormalizedName = "MAFADMIN"
                        },
                        new
                        {
                            Id = "m121b57c-9025-9223-e0f0-bdec765e3bgb",
                            ConcurrencyStamp = "la9a3b0g-8b4f-6218-91e0-4fd366e23f17",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Maximum Permissions",
                            Name = "KSIAdmin",
                            NormalizedName = "KSIADMIN"
                        },
                        new
                        {
                            Id = "m347b57d-8617-9224-g0h0-bdec765e3lml",
                            ConcurrencyStamp = "la9a3b0g-7b3f-8412-11e0-4fd366e23f18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Maximum Permissions",
                            Name = "YSSAdmin",
                            NormalizedName = "YSSADMIN"
                        },
                        new
                        {
                            Id = "m915b57e-2431-9225-i0j0-bdec765e3pgp",
                            ConcurrencyStamp = "la9a3b0g-6b2f-9864-21e0-4fd366e23f19",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Maximum Permissions",
                            Name = "RFLAdmin",
                            NormalizedName = "RFLADMIN"
                        },
                        new
                        {
                            Id = "m173b57f-8519-9226-k0l0-bdec765e3rir",
                            ConcurrencyStamp = "la9a3b0g-5b1f-7852-31e0-4fd366e23f20",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Maximum Permissions",
                            Name = "APEXAdmin",
                            NormalizedName = "APEXADMIN"
                        },
                        new
                        {
                            Id = "m354b57g-4013-9227-m0n0-bdec765e3oeo",
                            ConcurrencyStamp = "la9a3b0g-4b9f-4102-41e0-4fd366e23f21",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Maximum Permissions",
                            Name = "EDISONAdmin",
                            NormalizedName = "EDISONADMIN"
                        },
                        new
                        {
                            Id = "e858c58l-3251-9888-c1d1-bdec765e3pip",
                            ConcurrencyStamp = "ah8b4b9j-3n6o-3491-73e1-4fd800e23g17",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "MAFUserOfLineBalancing",
                            NormalizedName = "MAFUSEROFLINEBALANCING"
                        },
                        new
                        {
                            Id = "e858c58l-3252-9889-c2d2-bdec765e3pip",
                            ConcurrencyStamp = "ah8b4b9j-3n6o-3492-73e1-4fd800e23g17",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "MAFUserOfIncentive",
                            NormalizedName = "MAFUSEROFINCENTIVE"
                        },
                        new
                        {
                            Id = "e858c58l-3253-9890-c3d3-bdec765e3pip",
                            ConcurrencyStamp = "ah8b4b9j-3n6o-3493-73e1-4fd800e23g17",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "MAFUserOfSkillMatrix",
                            NormalizedName = "MAFUSEROFSKILLMATRIX"
                        },
                        new
                        {
                            Id = "e858c58l-3254-9891-c4d4-bdec765e3pip",
                            ConcurrencyStamp = "ah8b4b9j-3n6o-3494-73e1-4fd800e23g17",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "MAFUserOfSOT",
                            NormalizedName = "MAFUSEROFSOT"
                        },
                        new
                        {
                            Id = "e858c58l-3255-9892-c5d5-bdec765e3pip",
                            ConcurrencyStamp = "aar8b4b9j-3n6o-3495-73e1-4fd157e23g17",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "MAFUserOfArchive",
                            NormalizedName = "MAFUSEROFARCHIVE"
                        },
                        new
                        {
                            Id = "a212b59c-5209-3999-e1f1-bdec785e4lil",
                            ConcurrencyStamp = "eu5a3b0g-9c5g-9126-45e1-4fd366e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "KSIUserOfLineBalancing",
                            NormalizedName = "KSIUSEROFLINEBALANCING"
                        },
                        new
                        {
                            Id = "a212b59c-5210-4000-e2f2-bdec785e4lil",
                            ConcurrencyStamp = "eu5a3b0g-9c5g-9127-45e1-4fd366e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "KSIUserOfIncentive",
                            NormalizedName = "KSIUSEROFINCENTIVE"
                        },
                        new
                        {
                            Id = "a212b59c-5211-4001-e3f3-bdec785e4lil",
                            ConcurrencyStamp = "eu5a3b0g-9c5g-9128-45e1-4fd366e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "KSIUserOfSkillMatrix",
                            NormalizedName = "KSIUSEROFSKILLMATRIX"
                        },
                        new
                        {
                            Id = "a212b59c-5212-4002-e4f4-bdec785e4lil",
                            ConcurrencyStamp = "eu5a3b0g-9c5g-9129-45e1-4fd366e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "KSIUserOfSOT",
                            NormalizedName = "KSIUSEROFSOT"
                        },
                        new
                        {
                            Id = "a212b59c-5213-4003-e5f5-bdec785e4lil",
                            ConcurrencyStamp = "aar5a3b0g-9c5g-9130-99e1-4fd155e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "KSIUserOfArchive",
                            NormalizedName = "KSIUSEROFARCHIVE"
                        },
                        new
                        {
                            Id = "g734b69c-9461-6111-g1h1-bdec785e4imi",
                            ConcurrencyStamp = "ri5a3b0g-8d4j-2184-95e1-4fd352e23i19",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "YSSUserOfLineBalancing",
                            NormalizedName = "YSSUSEROFLINEBALANCING"
                        },
                        new
                        {
                            Id = "g734b69c-9462-6112-g2h2-bdec785e4imi",
                            ConcurrencyStamp = "ri5a3b0g-8d4j-2185-95e1-4fd352e23i19",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "YSSUserOfIncentive",
                            NormalizedName = "YSSUSEROFINCENTIVE"
                        },
                        new
                        {
                            Id = "g734b69c-9463-6113-g3h3-bdec785e4imi",
                            ConcurrencyStamp = "ri5a3b0g-8d4j-2186-95e1-4fd352e23i19",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "YSSUserOfSkillMatrix",
                            NormalizedName = "YSSUSEROFSKILLMATRIX"
                        },
                        new
                        {
                            Id = "g734b69c-9464-6114-g4h4-bdec785e4imi",
                            ConcurrencyStamp = "ri5a3b0g-8d4j-2187-95e1-4fd352e23i19",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "YSSUserOfSOT",
                            NormalizedName = "YSSUSEROFSOT"
                        },
                        new
                        {
                            Id = "g734b69c-9465-6115-g5h5-bdec785e4imi",
                            ConcurrencyStamp = "aar5a3b0g-8d4j-2188-95e1-4fd156e23i19",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "YSSUserOfArchive",
                            NormalizedName = "YSSUSEROFARCHIVE"
                        },
                        new
                        {
                            Id = "z323b59c-5209-5344-i1j1-bdec735e4gpg",
                            ConcurrencyStamp = "al5a3b0g-7c3p-4517-45e1-4fd377e23i20",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "RFLUserOfLineBalancing",
                            NormalizedName = "RFLUSEROFLINEBALANCING"
                        },
                        new
                        {
                            Id = "z323b59c-5210-5345-i2j2-bdec735e4gpg",
                            ConcurrencyStamp = "al5a3b0g-7c3p-4518-45e1-4fd377e23i20",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "RFLUserOfIncentive",
                            NormalizedName = "RFLUSEROFINCENTIVE"
                        },
                        new
                        {
                            Id = "z323b59c-5211-5346-i3j3-bdec735e4gpg",
                            ConcurrencyStamp = "al5a3b0g-7c3p-4519-45e1-4fd377e23i20",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "RFLUserOfSkillMatrix",
                            NormalizedName = "RFLUSEROFSKILLMATRIX"
                        },
                        new
                        {
                            Id = "z323b59c-5212-5347-i4j4-bdec735e4gpg",
                            ConcurrencyStamp = "al5a3b0g-7c3p-4520-45e1-4fd377e23i20",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "RFLUserOfSOT",
                            NormalizedName = "RFLUSEROFSOT"
                        },
                        new
                        {
                            Id = "z323b59c-5213-5348-i5j5-bdec735e4gpg",
                            ConcurrencyStamp = "aar5a3b0g-7c3p-4521-45e1-4fd158e23i20",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "RFLUserOfArchive",
                            NormalizedName = "RFLUSEROFARCHIVE"
                        },
                        new
                        {
                            Id = "x212b59c-3269-1666-k1l1-bdec785e4gig",
                            ConcurrencyStamp = "lq5a3b1g-6c2g-3254-93e1-4fd255e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "APEXUserOfLineBalancing",
                            NormalizedName = "APEXUSEROFLINEBALANCING"
                        },
                        new
                        {
                            Id = "x212b59c-3270-1667-k2l2-bdec785e4gig",
                            ConcurrencyStamp = "lq5a3b1g-6c2g-3255-93e1-4fd255e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "APEXUserOfIncentive",
                            NormalizedName = "APEXUSEROFINCENTIVE"
                        },
                        new
                        {
                            Id = "x212b59c-3271-1668-k3l3-bdec785e4gig",
                            ConcurrencyStamp = "lq5a3b1g-6c2g-3256-93e1-4fd255e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "APEXUserOfSkillMatrix",
                            NormalizedName = "APEXUSEROFSKILLMATRIX"
                        },
                        new
                        {
                            Id = "x212b59c-3272-1669-k4l4-bdec785e4gig",
                            ConcurrencyStamp = "lq5a3b1g-6c2g-3257-93e1-4fd255e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "APEXUserOfSOT",
                            NormalizedName = "APEXUSEROFSOT"
                        },
                        new
                        {
                            Id = "x212b59c-3273-1670-k5l5-bdec785e4gig",
                            ConcurrencyStamp = "aar5a3b1g-6c2g-3258-93e1-4fd159e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "APEXUserOfArchive",
                            NormalizedName = "APEXUSEROFARCHIVE"
                        },
                        new
                        {
                            Id = "v212b59c-6348-6121-m1n1-bdec785e4iki",
                            ConcurrencyStamp = "ql5a3b1g-5c2g-6512-81e1-4fd511e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "EDISONUserOfLineBalancing",
                            NormalizedName = "EDISONUSEROFLINEBALANCING"
                        },
                        new
                        {
                            Id = "v212b59c-6349-6122-m2n2-bdec785e4iki",
                            ConcurrencyStamp = "ql5a3b1g-5c2g-6513-81e1-4fd511e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "EDISONUserOfIncentive",
                            NormalizedName = "EDISONUSEROFINCENTIVE"
                        },
                        new
                        {
                            Id = "v212b59c-6350-6123-m3n3-bdec785e4iki",
                            ConcurrencyStamp = "ql5a3b1g-5c2g-6514-81e1-4fd511e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "EDISONUserOfSkillMatrix",
                            NormalizedName = "EDISONUSEROFSKILLMATRIX"
                        },
                        new
                        {
                            Id = "v212b59c-6351-6124-m4n4-bdec785e4iki",
                            ConcurrencyStamp = "ql5a3b1g-5c2g-6515-81e1-4fd511e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "EDISONUserOfSOT",
                            NormalizedName = "EDISONUSEROFSOT"
                        },
                        new
                        {
                            Id = "v212b59c-6352-6125-m5n5-bdec785e4iki",
                            ConcurrencyStamp = "aar5a3b1g-5c2g-6516-81e1-4fd160e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Several Permissions",
                            Name = "EDISONUserOfArchive",
                            NormalizedName = "EDISONUSEROFARCHIVE"
                        },
                        new
                        {
                            Id = "e858c58l-1212-4222-c2d2-bdec131e3pbp",
                            ConcurrencyStamp = "ah8b4b9j-3n6o-3491-73e1-4fd800e23g17",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Minimum Permissions",
                            Name = "MAFViewer",
                            NormalizedName = "MAFVIEWER"
                        },
                        new
                        {
                            Id = "a212b59c-3434-4333-e2f2-bdec132e4lbl",
                            ConcurrencyStamp = "eu5a3b0g-9c5g-9126-45e1-4fd366e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Minimum Permissions",
                            Name = "KSIViewer",
                            NormalizedName = "KSIVIEWER"
                        },
                        new
                        {
                            Id = "g734b69c-5656-4555-g2h2-bdec133e4ibi",
                            ConcurrencyStamp = "ri5a3b0g-8d4j-2184-95e1-4fd352e23i19",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Minimum Permissions",
                            Name = "YSSViewer",
                            NormalizedName = "YSSVIEWER"
                        },
                        new
                        {
                            Id = "z323b59c-7878-4666-i2j2-bdec134e4gbg",
                            ConcurrencyStamp = "al5a3b0g-7c3p-4517-45e1-4fd377e23i20",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Minimum Permissions",
                            Name = "RFLViewer",
                            NormalizedName = "RFLVIEWER"
                        },
                        new
                        {
                            Id = "x212b59c-9191-4777-k2l2-bdec135e4gbg",
                            ConcurrencyStamp = "lq5a3b1g-6c2g-3254-93e1-4fd255e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Minimum Permissions",
                            Name = "APEXViewer",
                            NormalizedName = "APEXVIEWER"
                        },
                        new
                        {
                            Id = "v212b59c-3113-4888-m2n2-bdec136e4ibi",
                            ConcurrencyStamp = "ql5a3b1g-5c2g-6512-81e1-4fd511e23i18",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has Minimum Permissions",
                            Name = "EDISONViewer",
                            NormalizedName = "EDISONVIEWER"
                        });
                });

            modelBuilder.Entity("Dynamo.Model.Common.Authentication.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<int>("FactoryId");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "8ab6ee62-f36c-48b6-ae27-dbb22cbfb507",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "26d21881-0a3a-44ab-aa4d-10664ace1e2d",
                            Email = "monir.hossain@decathlon.com",
                            EmailConfirmed = false,
                            FactoryId = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "MONIR.HOSSAIN@DECATHLON.COM",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEEO6XuvdZ4p/fzatnYaxaH4psRTnOEp3N+Ez6FFxAh1S76HPtt/YScM8RIguweFeoQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5TDMS5CNA2GYJK2URB4GDOCQI2NI7EHJ",
                            TwoFactorEnabled = false,
                            UserName = "SuperAdmin"
                        },
                        new
                        {
                            Id = "9cd7ff85-f36c-69b6-ea27-dbb23cbfb508",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "62d21881-0b3b-55ab-aa4d-61220ace1e2e",
                            Email = "info@neurostormsoft.com",
                            EmailConfirmed = false,
                            FactoryId = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "INFO@NEUROSTORMSOFT.COM",
                            NormalizedUserName = "NEUROSTORM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDNQpE8hqBcgCek1F6WkCX1siCTa4B6dSKD+ZjbxScznzTuQffacsPK9nKL7gK+3DQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6UEMS5CNA2GYLO2URB5GDOQQI2NI7FIL",
                            TwoFactorEnabled = false,
                            UserName = "NeuroStorm"
                        });
                });

            modelBuilder.Entity("Dynamo.Model.Common.CssClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CssClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "ToogleSideMenuClass"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Name = "Sidebar Radius"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Name = "Dark Navigation"
                        });
                });

            modelBuilder.Entity("Dynamo.Model.Common.Infrastructure.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsRead");

                    b.Property<string>("Message");

                    b.Property<string>("SentBy");

                    b.Property<string>("SentByUserName");

                    b.Property<string>("SentTo");

                    b.Property<string>("SentToUserName");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Dynamo.Model.Common.Infrastructure.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("Dynamo.Model.Common.Infrastructure.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdderId");

                    b.Property<string>("LinkAction");

                    b.Property<string>("LinkController");

                    b.Property<int>("NotificationTypeId");

                    b.Property<DateTime>("PostingTime");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Dynamo.Model.Common.Infrastructure.NotificationApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsRead");

                    b.Property<int>("NotificationId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("Dynamo.Model.Common.Infrastructure.NotificationGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("NotificationGroups");
                });

            modelBuilder.Entity("Dynamo.Model.Common.Infrastructure.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Event"
                        });
                });

            modelBuilder.Entity("Dynamo.Model.Common.UserProfiles.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .IsRequired();

                    b.Property<string>("City");

                    b.Property<string>("Nationality");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PhotoName");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "8ab6ee62-f36c-48b6-ae27-dbb22cbfb507",
                            PhotoName = "No File"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = "9cd7ff85-f36c-69b6-ea27-dbb23cbfb508",
                            PhotoName = "No File"
                        });
                });

            modelBuilder.Entity("Dynamo.Model.ELearnings.ELearning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfUpload");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("ELearningFileName1");

                    b.Property<string>("ELearningFileName2");

                    b.Property<int>("FactoryId");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("ELearnings");
                });

            modelBuilder.Entity("Dynamo.Model.Factories.Factory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Factories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Chittagong",
                            Name = "KSI",
                            PhoneNumber = "A-001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Chittagong",
                            Name = "YSS",
                            PhoneNumber = "A-002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Chittagong",
                            Name = "MAF",
                            PhoneNumber = "A-003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Chittagong",
                            Name = "RFL",
                            PhoneNumber = "A-004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Chittagong",
                            Name = "APEX",
                            PhoneNumber = "A-005"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Chittagong",
                            Name = "EDISON",
                            PhoneNumber = "A-006"
                        });
                });

            modelBuilder.Entity("Dynamo.Model.Factories.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LineNumber")
                        .IsRequired();

                    b.Property<int?>("SectionId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("Dynamo.Model.Factories.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FactoryId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("ProcessId");

                    b.Property<string>("ShortName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("ProcessId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.AchievedValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IncentiveVariableId");

                    b.Property<int>("LineIncentiveId");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.HasIndex("LineIncentiveId");

                    b.ToTable("AchievedValues");
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.IncentiveVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("IncentiveVariables");
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.LineIncentive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments");

                    b.Property<bool>("Enable");

                    b.Property<int>("LineId");

                    b.Property<DateTime>("LineIncentiveDateTime");

                    b.Property<double?>("Total");

                    b.HasKey("Id");

                    b.HasIndex("LineId")
                        .IsUnique();

                    b.ToTable("LineIncentives");
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.MonthlySectionEarningPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("MoneyPerPoint");

                    b.Property<int>("Month");

                    b.Property<int>("SectionId");

                    b.Property<double>("TargetPoint");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("MonthlySectionEarningPoints");
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.MonthlyVariableValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IncentiveVariableId");

                    b.Property<int>("Month");

                    b.Property<int>("SectionId");

                    b.Property<double>("Value");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("IncentiveVariableId");

                    b.HasIndex("SectionId");

                    b.ToTable("MonthlyVariableValues");
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.PointValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IncentiveVariableId");

                    b.Property<int>("LineIncentiveId");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.HasIndex("LineIncentiveId");

                    b.ToTable("PointValues");
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.TargetValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IncentiveVariableId");

                    b.Property<int>("LineIncentiveId");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.HasIndex("LineIncentiveId");

                    b.ToTable("TargetValues");
                });

            modelBuilder.Entity("Dynamo.Model.LineBalancing.LineBalancingState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("AllocatedTime1");

                    b.Property<double?>("AllocatedTime2");

                    b.Property<double?>("AllocatedTime3");

                    b.Property<double?>("AllocatedTime4");

                    b.Property<double?>("CycleTime1");

                    b.Property<double?>("CycleTime2");

                    b.Property<double?>("CycleTime3");

                    b.Property<double?>("CycleTime4");

                    b.Property<int>("MachineId");

                    b.Property<int>("OperationId");

                    b.Property<string>("OperationName");

                    b.Property<int?>("OperatorId1");

                    b.Property<int?>("OperatorId2");

                    b.Property<int?>("OperatorId3");

                    b.Property<int?>("OperatorId4");

                    b.Property<int?>("OperatorNo1");

                    b.Property<int?>("OperatorNo2");

                    b.Property<int?>("OperatorNo3");

                    b.Property<int?>("OperatorNo4");

                    b.Property<double?>("Output1");

                    b.Property<double?>("Output2");

                    b.Property<double?>("Output3");

                    b.Property<double?>("Output4");

                    b.Property<int>("ParticularLineBalancingId");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("OperationId");

                    b.HasIndex("ParticularLineBalancingId");

                    b.ToTable("LineBalancingStates");
                });

            modelBuilder.Entity("Dynamo.Model.LineBalancing.ParticularLineBalancing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ActualLineBalancingRatio");

                    b.Property<int>("LineId");

                    b.Property<int>("StandardOperationTimeId");

                    b.Property<string>("Who");

                    b.HasKey("Id");

                    b.HasIndex("LineId")
                        .IsUnique();

                    b.HasIndex("StandardOperationTimeId");

                    b.ToTable("ParticularLineBalancings");
                });

            modelBuilder.Entity("Dynamo.Model.Machines.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("BasicTiredness");

                    b.Property<double?>("ChangeBobin");

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<int>("FactoryId");

                    b.Property<double?>("Field1");

                    b.Property<double?>("Field2");

                    b.Property<double?>("Field3");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double?>("NoiseyEnvironment");

                    b.Property<double?>("Other");

                    b.Property<double?>("Physiology");

                    b.Property<double?>("StandWorking");

                    b.Property<double?>("Total");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Dynamo.Model.Operations.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FactoryId");

                    b.Property<int>("MachineId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("SectionId");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("MachineId");

                    b.HasIndex("SectionId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("Dynamo.Model.Operations.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("IdCardNumber")
                        .IsRequired();

                    b.Property<DateTime>("JoiningDate");

                    b.Property<int?>("LineId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<int>("SectionId");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("SectionId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("Dynamo.Model.Skills.SkillMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OperationId");

                    b.Property<int>("OperatorId");

                    b.Property<double>("RftScore");

                    b.Property<double>("SotScore");

                    b.Property<double>("StandardRft");

                    b.Property<double>("StandardSotInSecond");

                    b.Property<string>("TargetGrade")
                        .IsRequired();

                    b.Property<double?>("TargetMonth")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("OperatorId");

                    b.ToTable("SkillMatrixs");
                });

            modelBuilder.Entity("Dynamo.Model.Skills.SkillMatrixRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code");

                    b.Property<int>("FactoryId");

                    b.Property<string>("Level");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("SkillMatrixRanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            FactoryId = 1,
                            Level = ""
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            FactoryId = 1,
                            Level = ""
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            FactoryId = 1,
                            Level = ""
                        },
                        new
                        {
                            Id = 4,
                            Code = 4,
                            FactoryId = 1,
                            Level = ""
                        },
                        new
                        {
                            Id = 5,
                            Code = 5,
                            FactoryId = 1,
                            Level = ""
                        },
                        new
                        {
                            Id = 6,
                            Code = 1,
                            FactoryId = 2,
                            Level = ""
                        },
                        new
                        {
                            Id = 7,
                            Code = 2,
                            FactoryId = 2,
                            Level = ""
                        },
                        new
                        {
                            Id = 8,
                            Code = 3,
                            FactoryId = 2,
                            Level = ""
                        },
                        new
                        {
                            Id = 9,
                            Code = 4,
                            FactoryId = 2,
                            Level = ""
                        },
                        new
                        {
                            Id = 10,
                            Code = 5,
                            FactoryId = 2,
                            Level = ""
                        },
                        new
                        {
                            Id = 11,
                            Code = 1,
                            FactoryId = 3,
                            Level = ""
                        },
                        new
                        {
                            Id = 12,
                            Code = 2,
                            FactoryId = 3,
                            Level = ""
                        },
                        new
                        {
                            Id = 13,
                            Code = 3,
                            FactoryId = 3,
                            Level = ""
                        },
                        new
                        {
                            Id = 14,
                            Code = 4,
                            FactoryId = 3,
                            Level = ""
                        },
                        new
                        {
                            Id = 15,
                            Code = 5,
                            FactoryId = 3,
                            Level = ""
                        },
                        new
                        {
                            Id = 16,
                            Code = 1,
                            FactoryId = 4,
                            Level = ""
                        },
                        new
                        {
                            Id = 17,
                            Code = 2,
                            FactoryId = 4,
                            Level = ""
                        },
                        new
                        {
                            Id = 18,
                            Code = 3,
                            FactoryId = 4,
                            Level = ""
                        },
                        new
                        {
                            Id = 19,
                            Code = 4,
                            FactoryId = 4,
                            Level = ""
                        },
                        new
                        {
                            Id = 20,
                            Code = 5,
                            FactoryId = 4,
                            Level = ""
                        },
                        new
                        {
                            Id = 21,
                            Code = 1,
                            FactoryId = 5,
                            Level = ""
                        },
                        new
                        {
                            Id = 22,
                            Code = 2,
                            FactoryId = 5,
                            Level = ""
                        },
                        new
                        {
                            Id = 23,
                            Code = 3,
                            FactoryId = 5,
                            Level = ""
                        },
                        new
                        {
                            Id = 24,
                            Code = 4,
                            FactoryId = 5,
                            Level = ""
                        },
                        new
                        {
                            Id = 25,
                            Code = 5,
                            FactoryId = 5,
                            Level = ""
                        },
                        new
                        {
                            Id = 26,
                            Code = 1,
                            FactoryId = 6,
                            Level = ""
                        },
                        new
                        {
                            Id = 27,
                            Code = 2,
                            FactoryId = 6,
                            Level = ""
                        },
                        new
                        {
                            Id = 28,
                            Code = 3,
                            FactoryId = 6,
                            Level = ""
                        },
                        new
                        {
                            Id = 29,
                            Code = 4,
                            FactoryId = 6,
                            Level = ""
                        },
                        new
                        {
                            Id = 30,
                            Code = 5,
                            FactoryId = 6,
                            Level = ""
                        });
                });

            modelBuilder.Entity("Dynamo.Model.Sot.CalculationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CalculationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Not Done"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Done"
                        },
                        new
                        {
                            Id = 3,
                            Name = "In Progress"
                        });
                });

            modelBuilder.Entity("Dynamo.Model.Sot.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CalculationFileName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("DataSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalculationFileName = "STOPWATCH/VIDEO",
                            Name = "Supplier Vdo"
                        },
                        new
                        {
                            Id = 2,
                            CalculationFileName = "PACE",
                            Name = "Sam Pace"
                        });
                });

            modelBuilder.Entity("Dynamo.Model.Sot.ManualJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FactoryId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("ManualJobs");
                });

            modelBuilder.Entity("Dynamo.Model.Sot.ManualJobStandardOperationTimeItem", b =>
                {
                    b.Property<int>("StandardOperationTimeItemId");

                    b.Property<int>("ManualJobId");

                    b.Property<int>("Quantity");

                    b.Property<double>("Time");

                    b.HasKey("StandardOperationTimeItemId", "ManualJobId");

                    b.HasIndex("ManualJobId");

                    b.ToTable("ManualJobStandardOperationTimeItems");
                });

            modelBuilder.Entity("Dynamo.Model.Sot.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details");

                    b.Property<int>("FactoryId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("Dynamo.Model.Sot.SectionStandardOperationTime", b =>
                {
                    b.Property<int>("StandardOperationTimeId");

                    b.Property<int>("SectionId");

                    b.Property<double>("SotValue");

                    b.HasKey("StandardOperationTimeId", "SectionId");

                    b.HasIndex("SectionId");

                    b.ToTable("SectionStandardOperationTimes");
                });

            modelBuilder.Entity("Dynamo.Model.Sot.SignSport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FactoryId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("SignSports");
                });

            modelBuilder.Entity("Dynamo.Model.Sot.SotModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dipl");

                    b.Property<int>("FactoryId");

                    b.Property<string>("Name");

                    b.Property<string>("Photo");

                    b.Property<int>("ProcessId");

                    b.Property<int>("SignSportId");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("SignSportId");

                    b.ToTable("SotModels");
                });

            modelBuilder.Entity("Dynamo.Model.Sot.StandardOperationTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CalculationStatusId");

                    b.Property<int>("FactoryId");

                    b.Property<int>("SotModelId");

                    b.Property<int?>("ValidationStatusId");

                    b.HasKey("Id");

                    b.HasIndex("CalculationStatusId");

                    b.HasIndex("FactoryId");

                    b.HasIndex("SotModelId");

                    b.HasIndex("ValidationStatusId");

                    b.ToTable("StandardOperationTimes");
                });

            modelBuilder.Entity("Dynamo.Model.Sot.StandardOperationTimeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Cycle");

                    b.Property<double?>("CycleTime");

                    b.Property<int>("DataSourceId");

                    b.Property<string>("OperationCode");

                    b.Property<int>("OperationId");

                    b.Property<double?>("Rating");

                    b.Property<int>("SectionId");

                    b.Property<int?>("SerialNumber");

                    b.Property<double?>("Size");

                    b.Property<double?>("SotValue");

                    b.Property<int>("StandardOperationTimeId");

                    b.Property<string>("VideoLink");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("OperationId");

                    b.HasIndex("SectionId");

                    b.HasIndex("StandardOperationTimeId");

                    b.ToTable("StandardOperationTimeItems");
                });

            modelBuilder.Entity("Dynamo.Model.Sot.StandardOperationTimeSubItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("CycleEndTime");

                    b.Property<double?>("CycleStartTime");

                    b.Property<bool>("IsNeglected");

                    b.Property<int>("StandardOperationTimeItemId");

                    b.Property<double?>("Wastage1EndTime");

                    b.Property<double?>("Wastage1StartTime");

                    b.Property<double?>("Wastage2EndTime");

                    b.Property<double?>("Wastage2StartTime");

                    b.Property<double?>("Wastage3EndTime");

                    b.Property<double?>("Wastage3StartTime");

                    b.HasKey("Id");

                    b.HasIndex("StandardOperationTimeItemId");

                    b.ToTable("StandardOperationTimeSubItems");
                });

            modelBuilder.Entity("Dynamo.Model.Sot.ValidationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ValidationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Validated"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Not Validated"
                        },
                        new
                        {
                            Id = 3,
                            Name = "In Progress"
                        });
                });

            modelBuilder.Entity("Dynamo.Model.TPSProjects.TPSProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfUpload");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("FactoryId");

                    b.Property<string>("ProjectFileName1");

                    b.Property<string>("ProjectFileName2");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("TPSProjects");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "8ab6ee62-f36c-48b6-ae27-dbb22cbfb507",
                            RoleId = "f686b56a-6135-4221-a0b0-bdec547e3waw"
                        },
                        new
                        {
                            UserId = "9cd7ff85-f36c-69b6-ea27-dbb23cbfb508",
                            RoleId = "f686b56a-6135-4221-a0b0-bdec547e3waw"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Dynamo.Model.CICalendar.EventGuest", b =>
                {
                    b.HasOne("Dynamo.Model.CICalendar.CalendarEvent")
                        .WithMany("EventGuests")
                        .HasForeignKey("CalendarEventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Common.Authentication.ApplicationUser", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Factory", "Factory")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Common.Infrastructure.Notification", b =>
                {
                    b.HasOne("Dynamo.Model.Common.Infrastructure.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Common.Infrastructure.NotificationApplicationUser", b =>
                {
                    b.HasOne("Dynamo.Model.Common.Infrastructure.Notification", "Notification")
                        .WithMany("NotificationApplicationUsers")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Common.Infrastructure.NotificationGroup", b =>
                {
                    b.HasOne("Dynamo.Model.Common.Infrastructure.Group", "Group")
                        .WithMany("NotificationGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Common.UserProfiles.UserProfile", b =>
                {
                    b.HasOne("Dynamo.Model.Common.Authentication.ApplicationUser", "ApplicationUser")
                        .WithOne("UserProfile")
                        .HasForeignKey("Dynamo.Model.Common.UserProfiles.UserProfile", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.ELearnings.ELearning", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Factory", "Factory")
                        .WithMany("ELearnings")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Factories.Line", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Section", "Section")
                        .WithMany("Lines")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Factories.Section", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Factory", "Factory")
                        .WithMany("Sections")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Sot.Process", "Process")
                        .WithMany("Sections")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.AchievedValue", b =>
                {
                    b.HasOne("Dynamo.Model.Incentives.LineIncentive", "LineIncentive")
                        .WithMany()
                        .HasForeignKey("LineIncentiveId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.LineIncentive", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Line", "Line")
                        .WithOne("LineIncentive")
                        .HasForeignKey("Dynamo.Model.Incentives.LineIncentive", "LineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.MonthlySectionEarningPoint", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.MonthlyVariableValue", b =>
                {
                    b.HasOne("Dynamo.Model.Incentives.IncentiveVariable", "IncentiveVariable")
                        .WithMany()
                        .HasForeignKey("IncentiveVariableId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Factories.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.PointValue", b =>
                {
                    b.HasOne("Dynamo.Model.Incentives.LineIncentive", "LineIncentive")
                        .WithMany()
                        .HasForeignKey("LineIncentiveId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Incentives.TargetValue", b =>
                {
                    b.HasOne("Dynamo.Model.Incentives.LineIncentive", "LineIncentive")
                        .WithMany()
                        .HasForeignKey("LineIncentiveId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.LineBalancing.LineBalancingState", b =>
                {
                    b.HasOne("Dynamo.Model.Machines.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Operations.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.LineBalancing.ParticularLineBalancing", "ParticularLineBalancing")
                        .WithMany()
                        .HasForeignKey("ParticularLineBalancingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.LineBalancing.ParticularLineBalancing", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Line", "Line")
                        .WithOne("ParticularLineBalancings")
                        .HasForeignKey("Dynamo.Model.LineBalancing.ParticularLineBalancing", "LineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Sot.StandardOperationTime", "StandardOperationTime")
                        .WithMany("ParticularLineBalancings")
                        .HasForeignKey("StandardOperationTimeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Machines.Machine", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Factory", "Factory")
                        .WithMany("Machines")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Operations.Operation", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Factory", "Factory")
                        .WithMany("Operations")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Machines.Machine", "Machine")
                        .WithMany("Operations")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Factories.Section", "Section")
                        .WithMany("Operations")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Operations.Operator", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Line", "Line")
                        .WithMany("Operators")
                        .HasForeignKey("LineId");

                    b.HasOne("Dynamo.Model.Factories.Section", "Section")
                        .WithMany("Operators")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Skills.SkillMatrix", b =>
                {
                    b.HasOne("Dynamo.Model.Operations.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Operations.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Skills.SkillMatrixRange", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Factory", "Factory")
                        .WithMany("SkillMatrixRanges")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Sot.ManualJob", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Factory", "Factory")
                        .WithMany("ManualJobs")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Sot.ManualJobStandardOperationTimeItem", b =>
                {
                    b.HasOne("Dynamo.Model.Sot.ManualJob", "ManualJob")
                        .WithMany("ManualJobStandardOperationTimeItems")
                        .HasForeignKey("ManualJobId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Sot.StandardOperationTimeItem", "StandardOperationTimeItem")
                        .WithMany("ManualJobStandardOperationTimeItems")
                        .HasForeignKey("StandardOperationTimeItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Sot.Process", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Factory", "Factory")
                        .WithMany("Processes")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Sot.SectionStandardOperationTime", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Section", "Section")
                        .WithMany("SectionStandardOperationTimes")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Sot.StandardOperationTime", "StandardOperationTime")
                        .WithMany("SectionStandardOperationTimes")
                        .HasForeignKey("StandardOperationTimeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Sot.SignSport", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Factory", "Factory")
                        .WithMany("SignSports")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Sot.SotModel", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Factory", "Factory")
                        .WithMany("SotModels")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Sot.Process", "Process")
                        .WithMany("SotModels")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Sot.SignSport", "SignSport")
                        .WithMany("SotModels")
                        .HasForeignKey("SignSportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Sot.StandardOperationTime", b =>
                {
                    b.HasOne("Dynamo.Model.Sot.CalculationStatus", "CalculationStatus")
                        .WithMany("StandardOperationTimes")
                        .HasForeignKey("CalculationStatusId");

                    b.HasOne("Dynamo.Model.Factories.Factory", "Factory")
                        .WithMany("StandardOperationTimes")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Sot.SotModel", "SotModel")
                        .WithMany("StandardOperationTimes")
                        .HasForeignKey("SotModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Sot.ValidationStatus", "ValidationStatus")
                        .WithMany("StandardOperationTimes")
                        .HasForeignKey("ValidationStatusId");
                });

            modelBuilder.Entity("Dynamo.Model.Sot.StandardOperationTimeItem", b =>
                {
                    b.HasOne("Dynamo.Model.Sot.DataSource", "DataSource")
                        .WithMany("StandardOperationTimeItems")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Operations.Operation", "Operation")
                        .WithMany("StandardOperationTimeItems")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Factories.Section", "Section")
                        .WithMany("StandardOperationTimeItems")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Sot.StandardOperationTime", "StandardOperationTime")
                        .WithMany("StandardOperationTimeItems")
                        .HasForeignKey("StandardOperationTimeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.Sot.StandardOperationTimeSubItem", b =>
                {
                    b.HasOne("Dynamo.Model.Sot.StandardOperationTimeItem", "StandardOperationTimeItem")
                        .WithMany("StandardOperationTimeSubItems")
                        .HasForeignKey("StandardOperationTimeItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dynamo.Model.TPSProjects.TPSProject", b =>
                {
                    b.HasOne("Dynamo.Model.Factories.Factory", "Factory")
                        .WithMany("TPSProjects")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Dynamo.Model.Common.Authentication.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Dynamo.Model.Common.Authentication.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Dynamo.Model.Common.Authentication.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Dynamo.Model.Common.Authentication.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dynamo.Model.Common.Authentication.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Dynamo.Model.Common.Authentication.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
